"""Para encadear exceções em Python, você pode utilizar a cláusula raise dentro de um bloco except para lançar uma nova exceção em resposta a uma exceção capturada"""

